### ISSUE TITLE
Possible encoding issue when reading in files with special characters using file_index_read()

### ISSUE THREAD

**Issue by zchenmr** [GuiFabre/fabR#9]
fabR v2.0.1

When I try to read in files with special characters using `file_index_read`, this leads to an error: 
```
folder_name = file_index_read(index = index, file_path = "[path of folder]", assign = FALSE)
```
<img alt="image" src="https://github.com/GuiFabre/fabR/assets/106557160/be637691-d497-4db4-87c6-14530642c6a6">

Trying with `read_csv` also led to an error (shown below), but adding the argument `locale=locale(encoding="latin1")` worked so it seems like this could be an encoding issue.

<img alt="image" src="https://github.com/GuiFabre/fabR/assets/106557160/3ecd5992-6241-4eca-8911-153fd0370375">

Example of one of the files read: https://www.statcan.gc.ca/fra/programmes-statistiques/document/noc-cnp-2011-structure-fra.csv

**Comment by zchenmr** [comment]
fabR v2.0.2.0001

I tested again - this time, `file_index_read` was able to read the dataset but there were still warnings of parsing issues. After using both `file_index_read` and `read_csv` and comparing the results, the function `all.equal` returned TRUE, `identical` returned FALSE and `summary(comparedf)` did not show any differences in values between the two datasets. I also tried calling `problems` as suggested in the warning message, but this did not provide any information on what the parsing issue is.

![image](https://github.com/GuiFabre/fabR/assets/106557160/1c9f142f-a25e-495d-9f96-c61d0272c44d)

**Comment by GuiFabre** [comment]
Hello @zchenmr, Can you retry again ? The message may not be usefull at some point, but i silenced the intermediate steps that were throwing addititional messages in the console.
Can you check if the function still works ?
Thanks

**Comment by zchenmr** [comment]
I'm getting this error message now with `file_index_read`: 

![image](https://github.com/GuiFabre/fabR/assets/106557160/8dcc9222-497b-474e-b40d-c14fe18aa99b)

**Comment by GuiFabre** [comment]
Sorry to hear that. Could you try again for me ?
Thanks

**Comment by zchenmr** [comment]
The dataset is now being read without warning/error messages👍.

**Comment by GuiFabre** [comment]
perfect :)
